import type { FormulaSnippet } from '../types'

const A = "Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI."

export const isentropicNozzleSnippets: FormulaSnippet = {
  formulaId: 'isentropic-nozzle',
  assumptions: A,
  code: {
    python: "# Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nimport math\nMe = math.sqrt((2 / (gamma - 1)) * (pepc ** (-(gamma - 1) / gamma) - 1))\nAe_At = (1 / Me) * (((1 + (gamma - 1) / 2 * Me**2) / ((gamma + 1) / 2)) ** ((gamma + 1) / (2 * (gamma - 1))))\nve = math.sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pepc ** ((gamma - 1) / gamma)))\nIsp = ve / 9.80665",
    javascript: "// Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nconst Me = Math.sqrt((2 / (gamma - 1)) * (pepc ** (-(gamma - 1) / gamma) - 1))\nconst Ae_At = (1 / Me) * (((1 + (gamma - 1) / 2 * Me**2) / ((gamma + 1) / 2)) ** ((gamma + 1) / (2 * (gamma - 1))))\nconst ve = Math.sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pepc ** ((gamma - 1) / gamma)))\nconst Isp = ve / 9.80665",
    typescript: "// Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nconst Me = Math.sqrt((2 / (gamma - 1)) * (pepc ** (-(gamma - 1) / gamma) - 1))\nconst Ae_At = (1 / Me) * (((1 + (gamma - 1) / 2 * Me**2) / ((gamma + 1) / 2)) ** ((gamma + 1) / (2 * (gamma - 1))))\nconst ve = Math.sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pepc ** ((gamma - 1) / gamma)))\nconst Isp = ve / 9.80665",
    c: "/* Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI. */\nconst double Me = sqrt((2 / (gamma - 1)) * (pow(pepc, (-(gamma - 1) / gamma)) - 1));\nconst double Ae_At = (1 / Me) * (pow(((1 + (gamma - 1) / 2 * pow(Me, 2)) / ((gamma + 1) / 2)), ((gamma + 1) / (2 * (gamma - 1)))));\nconst double ve = sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pow(pepc, ((gamma - 1) / gamma))));\nconst double Isp = ve / 9.80665;",
    cpp: "// Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nconst double Me = sqrt((2 / (gamma - 1)) * (pow(pepc, (-(gamma - 1) / gamma)) - 1));\nconst double Ae_At = (1 / Me) * (pow(((1 + (gamma - 1) / 2 * pow(Me, 2)) / ((gamma + 1) / 2)), ((gamma + 1) / (2 * (gamma - 1)))));\nconst double ve = sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pow(pepc, ((gamma - 1) / gamma))));\nconst double Isp = ve / 9.80665;",
    rust: "// Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nlet Me = ((2.0_f64 / (gamma - 1.0_f64)) * ((pepc).powf((-(gamma - 1.0_f64) / gamma)) - 1.0_f64)).sqrt();\nlet Ae_At = (1.0_f64 / Me) * ((((1.0_f64 + (gamma - 1.0_f64) / 2.0_f64 * (Me).powi(2)) / ((gamma + 1.0_f64) / 2.0_f64))).powf(((gamma + 1.0_f64) / (2.0_f64 * (gamma - 1.0_f64)))));\nlet ve = ((2.0_f64 * gamma / (gamma - 1.0_f64)) * Rgas * Tc * (1.0_f64 - (pepc).powf(((gamma - 1.0_f64) / gamma)))).sqrt();\nlet Isp = ve / 9.80665_f64;",
    zig: "// Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nconst Me = std.math.sqrt((@as(f64, 2.0) / (gamma - @as(f64, 1.0))) * (std.math.pow(f64, pepc, (-(gamma - @as(f64, 1.0)) / gamma)) - @as(f64, 1.0)));\nconst Ae_At = (@as(f64, 1.0) / Me) * (std.math.pow(f64, ((@as(f64, 1.0) + (gamma - @as(f64, 1.0)) / @as(f64, 2.0) * std.math.pow(f64, Me, @as(f64, 2.0))) / ((gamma + @as(f64, 1.0)) / @as(f64, 2.0))), ((gamma + @as(f64, 1.0)) / (@as(f64, 2.0) * (gamma - @as(f64, 1.0))))));\nconst ve = std.math.sqrt((@as(f64, 2.0) * gamma / (gamma - @as(f64, 1.0))) * Rgas * Tc * (@as(f64, 1.0) - std.math.pow(f64, pepc, ((gamma - @as(f64, 1.0)) / gamma))));\nconst Isp = ve / @as(f64, 9.80665);",
    fortran: "! Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\n  Me = sqrt((2.0d0 / (gamma - 1.0d0)) * (pepc ** (-(gamma - 1.0d0) / gamma) - 1.0d0))\n  Ae_At = (1.0d0 / Me) * (((1.0d0 + (gamma - 1.0d0) / 2.0d0 * Me**2.0d0) / ((gamma + 1.0d0) / 2.0d0)) ** ((gamma + 1.0d0) / (2.0d0 * (gamma - 1.0d0))))\n  ve = sqrt((2.0d0 * gamma / (gamma - 1.0d0)) * Rgas * Tc * (1.0d0 - pepc ** ((gamma - 1.0d0) / gamma)))\n  Isp = ve / 9.80665d0",
    matlab: "% Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nMe = sqrt((2 / (gamma - 1)) * (pepc ^ (-(gamma - 1) / gamma) - 1))\nAe_At = (1 / Me) * (((1 + (gamma - 1) / 2 * Me^2) / ((gamma + 1) / 2)) ^ ((gamma + 1) / (2 * (gamma - 1))))\nve = sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pepc ^ ((gamma - 1) / gamma)))\nIsp = ve / 9.80665",
    julia: "# Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\nMe = sqrt((2 / (gamma - 1)) * (pepc ^ (-(gamma - 1) / gamma) - 1))\nAe_At = (1 / Me) * (((1 + (gamma - 1) / 2 * Me^2) / ((gamma + 1) / 2)) ^ ((gamma + 1) / (2 * (gamma - 1))))\nve = sqrt((2 * gamma / (gamma - 1)) * Rgas * Tc * (1 - pepc ^ ((gamma - 1) / gamma)))\nIsp = ve / 9.80665",
    latex: "% Ideal isentropic choked nozzle; perfect gas; steady 1-D; SI.\n\\[\nM_e=\\sqrt{\\frac{2}{\\gamma-1}\\left[\\left(\\frac{p_e}{p_c}\\right)^{-(\\gamma-1)/\\gamma}-1\\right]},\\quad\nv_e=\\sqrt{\\frac{2\\gamma}{\\gamma-1}RT_c\\left[1-\\left(\\frac{p_e}{p_c}\\right)^{(\\gamma-1)/\\gamma}\\right]}\n\\]",
  },
}
