import type { FormulaSnippet } from '../types'

const A = "δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI."

export const pumpCrankSnippets: FormulaSnippet = {
  formulaId: 'pump-crank',
  assumptions: A,
  code: {
    python:
      "# δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nimport math\ne = 1.0 + rp * vinf*vinf / mu\ndelta = 2.0 * math.asin(1.0 / e)\nvinx = -vinf * math.cos(pump)\nvinz = vinf * math.sin(pump)\nsx = vinx / vinf\nsz = vinz / vinf\nrn = math.sqrt(sz*sz + sx*sx)\nrx = (-sz) / rn\nrz = sx / rn\ncc = math.cos(crank)\nsc = math.sin(crank)\nkdv0 = sx*rx + sz*rz\nkx0 = rx*cc + sx*kdv0*(1.0-cc)\nky0 = (sz*rx - sx*rz)*sc\nkz0 = rz*cc + sz*kdv0*(1.0-cc)\nkn = math.sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0)\nkx = kx0/kn\nky = ky0/kn\nkz = kz0/kn\ncd = math.cos(delta)\nsd = math.sin(delta)\nkdv = kx*vinx + kz*vinz\nvoutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd)\nvouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd)\nvoutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd)\nvout = math.sqrt(voutx*voutx + vouty*vouty + voutz*voutz)",
    javascript:
      "// δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nconst e = 1.0 + rp * vinf*vinf / mu\nconst delta = 2.0 * Math.asin(1.0 / e)\nconst vinx = -vinf * Math.cos(pump)\nconst vinz = vinf * Math.sin(pump)\nconst sx = vinx / vinf\nconst sz = vinz / vinf\nlet rx = -sz, rz = sx\nconst rn = Math.hypot(rx, rz)\nrx /= rn; rz /= rn\nconst cc = Math.cos(crank), sc = Math.sin(crank)\nconst kdv0 = sx*rx + sz*rz\nlet kx = rx*cc + sx*kdv0*(1.0-cc)\nlet ky = (sz*rx - sx*rz)*sc\nlet kz = rz*cc + sz*kdv0*(1.0-cc)\nconst kn = Math.hypot(kx, ky, kz)\nkx /= kn; ky /= kn; kz /= kn\nconst cd = Math.cos(delta), sd = Math.sin(delta)\nconst kdv = kx*vinx + kz*vinz\nconst voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd)\nconst vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd)\nconst voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd)\nconst vout = Math.hypot(voutx, vouty, voutz)",
    typescript:
      "// δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nconst e = 1.0 + rp * vinf*vinf / mu\nconst delta = 2.0 * Math.asin(1.0 / e)\nconst vinx = -vinf * Math.cos(pump)\nconst vinz = vinf * Math.sin(pump)\nconst sx = vinx / vinf\nconst sz = vinz / vinf\nlet rx = -sz, rz = sx\nconst rn = Math.hypot(rx, rz)\nrx /= rn; rz /= rn\nconst cc = Math.cos(crank), sc = Math.sin(crank)\nconst kdv0 = sx*rx + sz*rz\nlet kx = rx*cc + sx*kdv0*(1.0-cc)\nlet ky = (sz*rx - sx*rz)*sc\nlet kz = rz*cc + sz*kdv0*(1.0-cc)\nconst kn = Math.hypot(kx, ky, kz)\nkx /= kn; ky /= kn; kz /= kn\nconst cd = Math.cos(delta), sd = Math.sin(delta)\nconst kdv = kx*vinx + kz*vinz\nconst voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd)\nconst vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd)\nconst voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd)\nconst vout = Math.hypot(voutx, vouty, voutz)",
    c: "/* δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI. */\nconst double e = 1.0 + rp * vinf*vinf / mu;\nconst double delta = 2.0 * asin(1.0 / e);\nconst double vinx = -vinf * cos(pump);\nconst double vinz = vinf * sin(pump);\nconst double sx = vinx / vinf;\nconst double sz = vinz / vinf;\nconst double rn = sqrt(sz*sz + sx*sx);\nconst double rx = (-sz) / rn;\nconst double rz = sx / rn;\nconst double cc = cos(crank), sc = sin(crank);\nconst double kdv0 = sx*rx + sz*rz;\nconst double kx0 = rx*cc + sx*kdv0*(1.0-cc);\nconst double ky0 = (sz*rx - sx*rz)*sc;\nconst double kz0 = rz*cc + sz*kdv0*(1.0-cc);\nconst double kn = sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0);\nconst double kx = kx0/kn, ky = ky0/kn, kz = kz0/kn;\nconst double cd = cos(delta), sd = sin(delta);\nconst double kdv = kx*vinx + kz*vinz;\nconst double voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd);\nconst double vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd);\nconst double voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd);\nconst double vout = sqrt(voutx*voutx + vouty*vouty + voutz*voutz);",
    cpp: "// δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nconst double e = 1.0 + rp * vinf*vinf / mu;\nconst double delta = 2.0 * asin(1.0 / e);\nconst double vinx = -vinf * cos(pump);\nconst double vinz = vinf * sin(pump);\nconst double sx = vinx / vinf;\nconst double sz = vinz / vinf;\nconst double rn = sqrt(sz*sz + sx*sx);\nconst double rx = (-sz) / rn;\nconst double rz = sx / rn;\nconst double cc = cos(crank), sc = sin(crank);\nconst double kdv0 = sx*rx + sz*rz;\nconst double kx0 = rx*cc + sx*kdv0*(1.0-cc);\nconst double ky0 = (sz*rx - sx*rz)*sc;\nconst double kz0 = rz*cc + sz*kdv0*(1.0-cc);\nconst double kn = sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0);\nconst double kx = kx0/kn, ky = ky0/kn, kz = kz0/kn;\nconst double cd = cos(delta), sd = sin(delta);\nconst double kdv = kx*vinx + kz*vinz;\nconst double voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd);\nconst double vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd);\nconst double voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd);\nconst double vout = sqrt(voutx*voutx + vouty*vouty + voutz*voutz);",
    rust: "// δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nlet e = 1.0_f64 + rp * vinf*vinf / mu;\nlet delta = 2.0_f64 * (1.0_f64 / e).asin();\nlet vinx = -vinf * (pump).cos();\nlet vinz = vinf * (pump).sin();\nlet sx = vinx / vinf;\nlet sz = vinz / vinf;\nlet rn = (sz*sz + sx*sx).sqrt();\nlet rx = (-sz) / rn;\nlet rz = sx / rn;\nlet cc = (crank).cos();\nlet sc = (crank).sin();\nlet kdv0 = sx*rx + sz*rz;\nlet kx0 = rx*cc + sx*kdv0*(1.0_f64-cc);\nlet ky0 = (sz*rx - sx*rz)*sc;\nlet kz0 = rz*cc + sz*kdv0*(1.0_f64-cc);\nlet kn = (kx0*kx0 + ky0*ky0 + kz0*kz0).sqrt();\nlet kx = kx0/kn;\nlet ky = ky0/kn;\nlet kz = kz0/kn;\nlet cd = (delta).cos();\nlet sd = (delta).sin();\nlet kdv = kx*vinx + kz*vinz;\nlet voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0_f64-cd);\nlet vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0_f64-cd);\nlet voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0_f64-cd);\nlet vout = (voutx*voutx + vouty*vouty + voutz*voutz).sqrt();",
    zig: "// δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\nconst e = @as(f64, 1.0) + rp * vinf*vinf / mu;\nconst delta = @as(f64, 2.0) * std.math.asin(@as(f64, 1.0) / e);\nconst vinx = -vinf * @cos(pump);\nconst vinz = vinf * @sin(pump);\nconst sx = vinx / vinf;\nconst sz = vinz / vinf;\nconst rn = @sqrt(sz*sz + sx*sx);\nconst rx = (-sz) / rn;\nconst rz = sx / rn;\nconst cc = @cos(crank);\nconst sc = @sin(crank);\nconst kdv0 = sx*rx + sz*rz;\nconst kx0 = rx*cc + sx*kdv0*(@as(f64, 1.0)-cc);\nconst ky0 = (sz*rx - sx*rz)*sc;\nconst kz0 = rz*cc + sz*kdv0*(@as(f64, 1.0)-cc);\nconst kn = @sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0);\nconst kx = kx0/kn;\nconst ky = ky0/kn;\nconst kz = kz0/kn;\nconst cd = @cos(delta);\nconst sd = @sin(delta);\nconst kdv = kx*vinx + kz*vinz;\nconst voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(@as(f64, 1.0)-cd);\nconst vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(@as(f64, 1.0)-cd);\nconst voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(@as(f64, 1.0)-cd);\nconst vout = @sqrt(voutx*voutx + vouty*vouty + voutz*voutz);",
    fortran:
      "! δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\n  e = 1.0d0 + rp * vinf*vinf / mu\n  delta = 2.0d0 * asin(1.0d0 / e)\n  vinx = -vinf * cos(pump)\n  vinz = vinf * sin(pump)\n  sx = vinx / vinf\n  sz = vinz / vinf\n  rn = sqrt(sz*sz + sx*sx)\n  rx = (-sz) / rn\n  rz = sx / rn\n  cc = cos(crank)\n  sc = sin(crank)\n  kdv0 = sx*rx + sz*rz\n  kx0 = rx*cc + sx*kdv0*(1.0d0-cc)\n  ky0 = (sz*rx - sx*rz)*sc\n  kz0 = rz*cc + sz*kdv0*(1.0d0-cc)\n  kn = sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0)\n  kx = kx0/kn\n  ky = ky0/kn\n  kz = kz0/kn\n  cd = cos(delta)\n  sd = sin(delta)\n  kdv = kx*vinx + kz*vinz\n  voutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0d0-cd)\n  vouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0d0-cd)\n  voutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0d0-cd)\n  vout = sqrt(voutx*voutx + vouty*vouty + voutz*voutz)",
    matlab:
      "% δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\ne = 1.0 + rp * vinf*vinf / mu\ndelta = 2.0 * asin(1.0 / e)\nvinx = -vinf * cos(pump)\nvinz = vinf * sin(pump)\nsx = vinx / vinf\nsz = vinz / vinf\nrn = sqrt(sz*sz + sx*sx)\nrx = (-sz) / rn\nrz = sx / rn\ncc = cos(crank)\nsc = sin(crank)\nkdv0 = sx*rx + sz*rz\nkx0 = rx*cc + sx*kdv0*(1.0-cc)\nky0 = (sz*rx - sx*rz)*sc\nkz0 = rz*cc + sz*kdv0*(1.0-cc)\nkn = sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0)\nkx = kx0/kn\nky = ky0/kn\nkz = kz0/kn\ncd = cos(delta)\nsd = sin(delta)\nkdv = kx*vinx + kz*vinz\nvoutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd)\nvouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd)\nvoutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd)\nvout = sqrt(voutx*voutx + vouty*vouty + voutz*voutz)",
    julia:
      "# δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\ne = 1.0 + rp * vinf*vinf / mu\ndelta = 2.0 * asin(1.0 / e)\nvinx = -vinf * cos(pump)\nvinz = vinf * sin(pump)\nsx = vinx / vinf\nsz = vinz / vinf\nrn = sqrt(sz*sz + sx*sx)\nrx = (-sz) / rn\nrz = sx / rn\ncc = cos(crank)\nsc = sin(crank)\nkdv0 = sx*rx + sz*rz\nkx0 = rx*cc + sx*kdv0*(1.0-cc)\nky0 = (sz*rx - sx*rz)*sc\nkz0 = rz*cc + sz*kdv0*(1.0-cc)\nkn = sqrt(kx0*kx0 + ky0*ky0 + kz0*kz0)\nkx = kx0/kn\nky = ky0/kn\nkz = kz0/kn\ncd = cos(delta)\nsd = sin(delta)\nkdv = kx*vinx + kz*vinz\nvoutx = vinx*cd + (ky*vinz)*sd + kx*kdv*(1.0-cd)\nvouty = (kz*vinx - kx*vinz)*sd + ky*kdv*(1.0-cd)\nvoutz = vinz*cd + (-ky*vinx)*sd + kz*kdv*(1.0-cd)\nvout = sqrt(voutx*voutx + vouty*vouty + voutz*voutz)",
    latex:
      "% δ=2 arcsin(1/e); rotate v∞ by δ about the cranked turn axis; SI.\n\\[\\delta=2\\arcsin(1/e),\\quad \\mathbf{v}_\\infty^{+}=R_{\\hat k}(\\delta)\\mathbf{v}_\\infty^{-}\\]",
  },
}
