import { lazy, Suspense, type ComponentType, type LazyExoticComponent } from 'react'

type LazyTool = LazyExoticComponent<ComponentType>

function L(loader: () => Promise<{ default: ComponentType }>): LazyTool {
  return lazy(loader)
}

const MAP: Record<string, LazyTool> = {
  'circular-orbit': L(() => import('./CircularOrbitTool').then((m) => ({ default: m.CircularOrbitTool }))),
  'hohmann': L(() => import('./HohmannTool').then((m) => ({ default: m.HohmannTool }))),
  'escape': L(() => import('./EscapeTool').then((m) => ({ default: m.EscapeTool }))),
  'bielliptic': L(() => import('./BiellipticTool').then((m) => ({ default: m.BiellipticTool }))),
  'plane-change': L(() => import('./PlaneChangeTool').then((m) => ({ default: m.PlaneChangeTool }))),
  'vis-viva': L(() => import('./VisVivaTool').then((m) => ({ default: m.VisVivaTool }))),
  'kepler-propagate': L(() => import('./KeplerPropagateTool').then((m) => ({ default: m.KeplerPropagateTool }))),
  'lambert': L(() => import('./LambertTool').then((m) => ({ default: m.LambertTool }))),
  'rv-elements': L(() => import('./RvElementsTool').then((m) => ({ default: m.RvElementsTool }))),
  'apsides': L(() => import('./ApsidesTool').then((m) => ({ default: m.ApsidesTool }))),
  'sgp4': L(() => import('./Sgp4Tool').then((m) => ({ default: m.Sgp4Tool }))),
  'look-angles': L(() => import('./LookAnglesTool').then((m) => ({ default: m.LookAnglesTool }))),
  'pass-predict': L(() => import('./PassPredictTool').then((m) => ({ default: m.PassPredictTool }))),
  'j2-drift': L(() => import('./J2DriftTool').then((m) => ({ default: m.J2DriftTool }))),
  'rocket-equation': L(() => import('./RocketEquationTool').then((m) => ({ default: m.RocketEquationTool }))),
  'multi-stage': L(() => import('./MultiStageTool').then((m) => ({ default: m.MultiStageTool }))),
  'plotter': L(() => import('./PlotterTool').then((m) => ({ default: m.PlotterTool }))),
  'units': L(() => import('./UnitsTool').then((m) => ({ default: m.UnitsTool }))),
  'bodies': L(() => import('./BodiesTool').then((m) => ({ default: m.BodiesTool }))),
  'launch-azimuth': L(() => import('./LaunchAzimuthTool').then((m) => ({ default: m.LaunchAzimuthTool }))),
  'sso': L(() => import('./SsoTool').then((m) => ({ default: m.SsoTool }))),
  'dynamic-pressure': L(() => import('./DynamicPressureTool').then((m) => ({ default: m.DynamicPressureTool }))),
  'cw-rendezvous': L(() => import('./CwRendezvousTool').then((m) => ({ default: m.CwRendezvousTool }))),
  'link-budget': L(() => import('./LinkBudgetTool').then((m) => ({ default: m.LinkBudgetTool }))),
  'phasing': L(() => import('./PhasingTool').then((m) => ({ default: m.PhasingTool }))),
  'metabolic-load': L(() => import('./MetabolicLoadTool').then((m) => ({ default: m.MetabolicLoadTool }))),
  'cabin-atmosphere': L(() => import('./CabinAtmosphereTool').then((m) => ({ default: m.CabinAtmosphereTool }))),
  'lioh-scrubber': L(() => import('./LiohScrubberTool').then((m) => ({ default: m.LiohScrubberTool }))),
  'cabin-leak': L(() => import('./CabinLeakTool').then((m) => ({ default: m.CabinLeakTool }))),
  'thermal-loop': L(() => import('./ThermalLoopTool').then((m) => ({ default: m.ThermalLoopTool }))),
  'custom-body': L(() => import('./CustomBodyTool').then((m) => ({ default: m.CustomBodyTool }))),
  'hyperbolic-c3': L(() => import('./HyperbolicC3Tool').then((m) => ({ default: m.HyperbolicC3Tool }))),
  'hohmann-plane': L(() => import('./HohmannPlaneTool').then((m) => ({ default: m.HohmannPlaneTool }))),
  'propellant-mass': L(() => import('./PropellantMassTool').then((m) => ({ default: m.PropellantMassTool }))),
  'ideal-thrust': L(() => import('./IdealThrustTool').then((m) => ({ default: m.IdealThrustTool }))),
  'soi': L(() => import('./SoiTool').then((m) => ({ default: m.SoiTool }))),
  'synodic-period': L(() => import('./SynodicPeriodTool').then((m) => ({ default: m.SynodicPeriodTool }))),
  'eclipse-duration': L(() => import('./EclipseDurationTool').then((m) => ({ default: m.EclipseDurationTool }))),
  'light-time': L(() => import('./LightTimeTool').then((m) => ({ default: m.LightTimeTool }))),
  'solar-pressure': L(() => import('./SolarPressureTool').then((m) => ({ default: m.SolarPressureTool }))),
  'ballistic-drag': L(() => import('./BallisticDragTool').then((m) => ({ default: m.BallisticDragTool }))),
  'circularize': L(() => import('./CircularizeTool').then((m) => ({ default: m.CircularizeTool }))),
  'geo-orbit': L(() => import('./GeoOrbitTool').then((m) => ({ default: m.GeoOrbitTool }))),
  'delta-a-burn': L(() => import('./DeltaABurnTool').then((m) => ({ default: m.DeltaABurnTool }))),
  'plane-change-apo': L(() => import('./PlaneChangeApoTool').then((m) => ({ default: m.PlaneChangeApoTool }))),
  'delta-v-budget': L(() => import('./DeltaVBudgetTool').then((m) => ({ default: m.DeltaVBudgetTool }))),
  'heat-flux': L(() => import('./HeatFluxTool').then((m) => ({ default: m.HeatFluxTool }))),
  'coelliptic': L(() => import('./CoellipticTool').then((m) => ({ default: m.CoellipticTool }))),
  'los-range-rate': L(() => import('./LosRangeRateTool').then((m) => ({ default: m.LosRangeRateTool }))),
  'oberth': L(() => import('./OberthTool').then((m) => ({ default: m.OberthTool }))),
  'horizon-range': L(() => import('./HorizonRangeTool').then((m) => ({ default: m.HorizonRangeTool }))),
  'antenna-beamwidth': L(() => import('./AntennaBeamwidthTool').then((m) => ({ default: m.AntennaBeamwidthTool }))),
  'deorbit': L(() => import('./DeorbitTool').then((m) => ({ default: m.DeorbitTool }))),
  'equal-stage': L(() => import('./EqualStageTool').then((m) => ({ default: m.EqualStageTool }))),
  'mean-motion': L(() => import('./MeanMotionTool').then((m) => ({ default: m.MeanMotionTool }))),
  'solar-array': L(() => import('./SolarArrayTool').then((m) => ({ default: m.SolarArrayTool }))),
  'battery': L(() => import('./BatteryTool').then((m) => ({ default: m.BatteryTool }))),
  'rcs': L(() => import('./RcsTool').then((m) => ({ default: m.RcsTool }))),
  'angular-diameter': L(() => import('./AngularDiameterTool').then((m) => ({ default: m.AngularDiameterTool }))),
  'diffraction': L(() => import('./DiffractionTool').then((m) => ({ default: m.DiffractionTool }))),
  'thermal-rad': L(() => import('./ThermalRadTool').then((m) => ({ default: m.ThermalRadTool }))),
  'drag-force': L(() => import('./DragForceTool').then((m) => ({ default: m.DragForceTool }))),
  'reaction-wheel': L(() => import('./ReactionWheelTool').then((m) => ({ default: m.ReactionWheelTool }))),
  'apo-raise': L(() => import('./ApoRaiseTool').then((m) => ({ default: m.ApoRaiseTool }))),
  'ground-track': L(() => import('./GroundTrackTool').then((m) => ({ default: m.GroundTrackTool }))),
  'along-track': L(() => import('./AlongTrackTool').then((m) => ({ default: m.AlongTrackTool }))),
  'period-match': L(() => import('./PeriodMatchTool').then((m) => ({ default: m.PeriodMatchTool }))),
  'eclipse-beta': L(() => import('./EclipseBetaTool').then((m) => ({ default: m.EclipseBetaTool }))),
  'hohmann-time': L(() => import('./HohmannTimeTool').then((m) => ({ default: m.HohmannTimeTool }))),
  'orbital-energy': L(() => import('./EnergyTool').then((m) => ({ default: m.EnergyTool }))),
  'true-anomaly': L(() => import('./TrueAnomalyTool').then((m) => ({ default: m.TrueAnomalyTool }))),
  'flyby-speed': L(() => import('./FlybySpeedTool').then((m) => ({ default: m.FlybySpeedTool }))),
  'nodal-period': L(() => import('./NodalPeriodTool').then((m) => ({ default: m.NodalPeriodTool }))),
  'eccentric-anomaly': L(() => import('./EccentricAnomalyTool').then((m) => ({ default: m.EccentricAnomalyTool }))),
  'scale-height': L(() => import('./ScaleHeightTool').then((m) => ({ default: m.ScaleHeightTool }))),
  'rendezvous-catchup': L(() => import('./RendezvousPhasingSimpleTool').then((m) => ({ default: m.RendezvousPhasingSimpleTool }))),
  'impulse-budget': L(() => import('./ImpulseBitBudgetTool').then((m) => ({ default: m.ImpulseBitBudgetTool }))),
  'sso-period': L(() => import('./SunSyncPeriodTool').then((m) => ({ default: m.SunSyncPeriodTool }))),
  'mass-ratio-stack': L(() => import('./MassRatioStagesTool').then((m) => ({ default: m.MassRatioStagesTool }))),
  'critical-inclination': L(() => import('./CriticalInclinationTool').then((m) => ({ default: m.CriticalInclinationTool }))),
  'relative-period': L(() => import('./RelativePeriodTool').then((m) => ({ default: m.RelativePeriodTool }))),
  'energy-vinf': L(() => import('./HyperbolicExcessFromEnergyTool').then((m) => ({ default: m.HyperbolicExcessFromEnergyTool }))),
  'geo-light-time': L(() => import('./CommDelayGeoTool').then((m) => ({ default: m.CommDelayGeoTool }))),
  'payload-fraction': L(() => import('./PayloadFractionTool').then((m) => ({ default: m.PayloadFractionTool }))),
  'specific-angular-momentum': L(() => import('./SpecificAngularMomentumTool').then((m) => ({ default: m.SpecificAngularMomentumTool }))),
  'escape-margin': L(() => import('./EnergyMarginTool').then((m) => ({ default: m.EnergyMarginTool }))),
  'spherical-distance': L(() => import('./SphericalDistanceTool').then((m) => ({ default: m.SphericalDistanceTool }))),
  'elevation-azimuth': L(() => import('./ElevationAzimuthTool').then((m) => ({ default: m.ElevationAzimuthTool }))),
  'vector-angle': L(() => import('./VectorAngleTool').then((m) => ({ default: m.VectorAngleTool }))),
  'helio-hohmann': L(() => import('./HelioHohmannTool').then((m) => ({ default: m.HelioHohmannTool }))),
  'patched-conic-depart': L(() => import('./PatchedConicDepartTool').then((m) => ({ default: m.PatchedConicDepartTool }))),
  'surface-access': L(() => import('./SurfaceAccessTool').then((m) => ({ default: m.SurfaceAccessTool }))),
  'orbit-3d': L(() => import('./Orbit3dTool').then((m) => ({ default: m.Orbit3dTool }))),
  'isentropic-nozzle': L(() => import('./IsentropicNozzleTool').then((m) => ({ default: m.IsentropicNozzleTool }))),
  'characteristic-velocity-cstar': L(() => import('./CharacteristicVelocityCstarTool').then((m) => ({ default: m.CharacteristicVelocityCstarTool }))),
  'throat-area-sizing': L(() => import('./ThroatAreaSizingTool').then((m) => ({ default: m.ThroatAreaSizingTool }))),
  'rocket-thrust-chamber': L(() => import('./RocketThrustChamberTool').then((m) => ({ default: m.RocketThrustChamberTool }))),
  'mixture-ratio': L(() => import('./MixtureRatioTool').then((m) => ({ default: m.MixtureRatioTool }))),
  'tank-ullage': L(() => import('./TankUllageTool').then((m) => ({ default: m.TankUllageTool }))),
  'blowdown-tank': L(() => import('./BlowdownTankTool').then((m) => ({ default: m.BlowdownTankTool }))),
  'propellant-density-impulse': L(() => import('./PropellantDensityImpulseTool').then((m) => ({ default: m.PropellantDensityImpulseTool }))),
  'cold-gas-thrust': L(() => import('./ColdGasThrustTool').then((m) => ({ default: m.ColdGasThrustTool }))),
  'ion-thruster-efficiency': L(() => import('./IonThrusterEfficiencyTool').then((m) => ({ default: m.IonThrusterEfficiencyTool }))),
  'hall-thruster-isp': L(() => import('./HallThrusterIspTool').then((m) => ({ default: m.HallThrusterIspTool }))),
  'gnss-pseudorange': L(() => import('./GnssPseudorangeTool').then((m) => ({ default: m.GnssPseudorangeTool }))),
  'gnss-geometry-gdop': L(() => import('./GnssGeometryGdopTool').then((m) => ({ default: m.GnssGeometryGdopTool }))),
  'laser-link-budget': L(() => import('./LaserLinkBudgetTool').then((m) => ({ default: m.LaserLinkBudgetTool }))),
  'laser-pointing-jitter': L(() => import('./LaserPointingJitterTool').then((m) => ({ default: m.LaserPointingJitterTool }))),
  'laser-time-of-flight': L(() => import('./LaserTimeOfFlightTool').then((m) => ({ default: m.LaserTimeOfFlightTool }))),
  'impedance-matching': L(() => import('./ImpedanceMatchingTool').then((m) => ({ default: m.ImpedanceMatchingTool }))),
  'antenna-gain-effective': L(() => import('./AntennaGainEffectiveTool').then((m) => ({ default: m.AntennaGainEffectiveTool }))),
  'doppler-shift-leo': L(() => import('./DopplerShiftLeoTool').then((m) => ({ default: m.DopplerShiftLeoTool }))),
  'radar-equation': L(() => import('./RadarEquationTool').then((m) => ({ default: m.RadarEquationTool }))),
  'rain-attenuation-simple': L(() => import('./RainAttenuationSimpleTool').then((m) => ({ default: m.RainAttenuationSimpleTool }))),
  'ttc-ebno': L(() => import('./TtcEbnoTool').then((m) => ({ default: m.TtcEbnoTool }))),
  'optical-ber-q': L(() => import('./OpticalBerQTool').then((m) => ({ default: m.OpticalBerQTool }))),
  'gnss-troposphere-delay': L(() => import('./GnssTroposphereDelayTool').then((m) => ({ default: m.GnssTroposphereDelayTool }))),
  'free-fall-time': L(() => import('./FreeFallTimeTool').then((m) => ({ default: m.FreeFallTimeTool }))),
  'ballistic-range': L(() => import('./BallisticRangeTool').then((m) => ({ default: m.BallisticRangeTool }))),
  'terminal-velocity': L(() => import('./TerminalVelocityTool').then((m) => ({ default: m.TerminalVelocityTool }))),
  'parachute-descent': L(() => import('./ParachuteDescentTool').then((m) => ({ default: m.ParachuteDescentTool }))),
  'coordinated-turn-bank': L(() => import('./CoordinatedTurnBankTool').then((m) => ({ default: m.CoordinatedTurnBankTool }))),
  'slew-rate-pointing': L(() => import('./SlewRatePointingTool').then((m) => ({ default: m.SlewRatePointingTool }))),
  'magnetic-torque': L(() => import('./MagneticTorqueTool').then((m) => ({ default: m.MagneticTorqueTool }))),
  'gravity-gradient-torque': L(() => import('./GravityGradientTorqueTool').then((m) => ({ default: m.GravityGradientTorqueTool }))),
  'rw-momentum-capacity': L(() => import('./RwMomentumCapacityTool').then((m) => ({ default: m.RwMomentumCapacityTool }))),
  'sun-sensor-cone': L(() => import('./SunSensorConeTool').then((m) => ({ default: m.SunSensorConeTool }))),
  'star-tracker-noise': L(() => import('./StarTrackerNoiseTool').then((m) => ({ default: m.StarTrackerNoiseTool }))),
  'constellation-walker': L(() => import('./ConstellationWalkerTool').then((m) => ({ default: m.ConstellationWalkerTool }))),
  'coverage-swath': L(() => import('./CoverageSwathTool').then((m) => ({ default: m.CoverageSwathTool }))),
  'revisit-time-simple': L(() => import('./RevisitTimeSimpleTool').then((m) => ({ default: m.RevisitTimeSimpleTool }))),
  'geo-stationkeeping-dv': L(() => import('./GeoStationkeepingDvTool').then((m) => ({ default: m.GeoStationkeepingDvTool }))),
  'geo-propellant-budget': L(() => import('./GeoPropellantBudgetTool').then((m) => ({ default: m.GeoPropellantBudgetTool }))),
  'drag-make-up-dv': L(() => import('./DragMakeUpDvTool').then((m) => ({ default: m.DragMakeUpDvTool }))),
  'tisserand-parameter': L(() => import('./TisserandParameterTool').then((m) => ({ default: m.TisserandParameterTool }))),
  'eps-orbit-average': L(() => import('./EpsOrbitAverageTool').then((m) => ({ default: m.EpsOrbitAverageTool }))),
  'relativity-clock-rate': L(() => import('./RelativityClockRateTool').then((m) => ({ default: m.RelativityClockRateTool }))),
  'gnss-ionosphere-klobuchar': L(() => import('./GnssIonosphereKlobucharTool').then((m) => ({ default: m.GnssIonosphereKlobucharTool }))),
  'optical-gsd': L(() => import('./OpticalGsdTool').then((m) => ({ default: m.OpticalGsdTool }))),
  'solar-sail-accel': L(() => import('./SolarSailAccelTool').then((m) => ({ default: m.SolarSailAccelTool }))),
  'finite-burn-dv': L(() => import('./FiniteBurnDvTool').then((m) => ({ default: m.FiniteBurnDvTool }))),
  'b-plane-impact': L(() => import('./BPlaneImpactTool').then((m) => ({ default: m.BPlaneImpactTool }))),
  'cr3bp-jacobi': L(() => import('./Cr3bpJacobiTool').then((m) => ({ default: m.Cr3bpJacobiTool }))),
  'orbit-lifetime-rough': L(() => import('./OrbitLifetimeRoughTool').then((m) => ({ default: m.OrbitLifetimeRoughTool }))),
  'geo-drift-rate': L(() => import('./GeoDriftRateTool').then((m) => ({ default: m.GeoDriftRateTool }))),
  'stefan-boltzmann': L(() => import('./StefanBoltzmannTool').then((m) => ({ default: m.StefanBoltzmannTool }))),
  'wien-peak': L(() => import('./WienPeakTool').then((m) => ({ default: m.WienPeakTool }))),
  'thruster-impulse-bit': L(() => import('./ThrusterImpulseBitTool').then((m) => ({ default: m.ThrusterImpulseBitTool }))),
  'arg-perigee-drift-j2': L(() => import('./ArgPerigeeDriftJ2Tool').then((m) => ({ default: m.ArgPerigeeDriftJ2Tool }))),
  'sar-azimuth-resolution': L(() => import('./SarAzimuthResolutionTool').then((m) => ({ default: m.SarAzimuthResolutionTool }))),
  'radar-range-resolution': L(() => import('./RadarRangeResolutionTool').then((m) => ({ default: m.RadarRangeResolutionTool }))),
  'link-margin': L(() => import('./LinkMarginTool').then((m) => ({ default: m.LinkMarginTool }))),
  'aerobraking-pass': L(() => import('./AerobrakingPassTool').then((m) => ({ default: m.AerobrakingPassTool }))),
  'diffraction-limit': L(() => import('./DiffractionLimitTool').then((m) => ({ default: m.DiffractionLimitTool }))),
  'panel-eol-power': L(() => import('./PanelEolPowerTool').then((m) => ({ default: m.PanelEolPowerTool }))),
  'magnetorquer-moment': L(() => import('./MagnetorquerMomentTool').then((m) => ({ default: m.MagnetorquerMomentTool }))),
  'hyperbolic-eccentricity': L(() => import('./HyperbolicEccentricityTool').then((m) => ({ default: m.HyperbolicEccentricityTool }))),
  'capture-circularize': L(() => import('./CaptureCircularizeTool').then((m) => ({ default: m.CaptureCircularizeTool }))),
  'gravity-loss': L(() => import('./GravityLossTool').then((m) => ({ default: m.GravityLossTool }))),
  'battery-dod': L(() => import('./BatteryDodTool').then((m) => ({ default: m.BatteryDodTool }))),
  'umbra-length': L(() => import('./UmbraLengthTool').then((m) => ({ default: m.UmbraLengthTool }))),
  'mean-anomaly-from-e': L(() => import('./MeanAnomalyFromETool').then((m) => ({ default: m.MeanAnomalyFromETool }))),
  'flight-path-angle': L(() => import('./FlightPathAngleTool').then((m) => ({ default: m.FlightPathAngleTool }))),
  'hoop-stress': L(() => import('./HoopStressTool').then((m) => ({ default: m.HoopStressTool }))),
  'exponential-density': L(() => import('./ExponentialDensityTool').then((m) => ({ default: m.ExponentialDensityTool }))),
  'hill-sphere': L(() => import('./HillSphereTool').then((m) => ({ default: m.HillSphereTool }))),
  'edelbaum-dv': L(() => import('./EdelbaumDvTool').then((m) => ({ default: m.EdelbaumDvTool }))),
  'repeating-ground-track': L(() => import('./RepeatingGroundTrackTool').then((m) => ({ default: m.RepeatingGroundTrackTool }))),
  'pointing-budget-rss': L(() => import('./PointingBudgetRssTool').then((m) => ({ default: m.PointingBudgetRssTool }))),
  'boiloff-rate': L(() => import('./BoiloffRateTool').then((m) => ({ default: m.BoiloffRateTool }))),
  'residual-dipole-torque': L(() => import('./ResidualDipoleTorqueTool').then((m) => ({ default: m.ResidualDipoleTorqueTool }))),
  'solar-flux-distance': L(() => import('./SolarFluxDistanceTool').then((m) => ({ default: m.SolarFluxDistanceTool }))),
  'nyquist-rate': L(() => import('./NyquistRateTool').then((m) => ({ default: m.NyquistRateTool }))),
  'data-volume': L(() => import('./DataVolumeTool').then((m) => ({ default: m.DataVolumeTool }))),
  'earth-ir-flux': L(() => import('./EarthIrFluxTool').then((m) => ({ default: m.EarthIrFluxTool }))),
}

type Props = { id: string }

export function ToolRenderer({ id }: Props) {
  const Cmp = MAP[id]
  if (!Cmp) {
    return (
      <p className="sidus-card p-5 font-mono text-sm text-muted">
        Unknown tool id: check the catalog registration.
      </p>
    )
  }
  return (
    <Suspense
      fallback={
        <p className="font-mono text-sm text-muted" aria-live="polite">
          Loading tool…
        </p>
      }
    >
      <Cmp />
    </Suspense>
  )
}
